Games/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
path('', views.cart_detail, name='cart_detail'),
path('remove/<uuid:product_id>/',views.cart_remove, name='cart_remove'),
path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

search_app/urls.py
from django.urls import path
from .views import SearchResultsListView

app_name='search_app'

urlpatterns = [
 path('', SearchResultsListView.as_view(), name='searchResult'),
]

shop/urls.py
from django.urls import path
from .import views
app_name = 'shop'

urlpatterns = [
    path('', views.index, name = 'home'),
    path('<uuid:category_id>/', views.prod_list, name = 'products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>', views.product_detail, name = 'product_detail'),
    path('bestsellers/', views.bestseller, name = 'bestsellers'),
]

shop/models.py
from django.db import models
import uuid
from django.urls import reverse

class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:products_by_category', args=[self.id])

    def __str__(self):
        return self.name

class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.category.id, self.id])

    def __str__(self):
        return self.name
    
class Bestseller(models.Model):
        id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
        product = models.ForeignKey(Product, on_delete=models.CASCADE)

        class Meta:
            ordering = ('product',)
            verbose_name = 'bestseller'
            verbose_name_plural = 'bestsellers'

        def get_absolute_url(self):
            return reverse('shop:Bestseller', args=[self.product.id, self.id])


shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Bestseller
from django.core.paginator import Paginator, EmptyPage, InvalidPage

def index(request):
    return render(request, 'home.html')

def prod_list(request, category_id=None):
    category = None
    products = Product.objects.filter(available=True)

    if category_id:
        category = get_object_or_404(Category, id=category_id)
        products = Product.objects.filter(category=category, available=True)

    paginator = Paginator(products, 4)

    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/catagory.html', {'category': category, 'prods': products})

def product_detail(request, category_id, product_id):
    product = get_object_or_404(Product, category_id=category_id, id=product_id)
    return render(request, 'shop/product.html', {'product': product})

def bestseller(request):
    bestsellers = Bestseller.objects.select_related('product').filter(product__available=True)
    products = Product.objects.filter(id__in=bestsellers.values_list('product_id', flat=True))
    return render(request, 'shop/bestsellers.html', {'bestsellers': bestsellers, 'prods': products})

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
        crossorigin="anonymous"
        
    />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" 
crossorigin="anonymous">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
    <body>
        <div class="base px-5">
            {% include 'header.html' %}
            {% include 'navbar.html' %}
            {% block content %}
            {% endblock %}
            {% include 'footer.html' %}
        </div>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous">
        </script>
        <script src="https://kit.fontawesome.com/71e0b3e869.js" crossorigin="anonymous"></script>
    </body>

</html>

shop/templates/footer.html
<div class="footer d-flex text-light">
    <p>&copy; Use of this Web site constitutes acceptance of the Terms and Conditions and Privacy policy. All copyrights, trade marks, service marks belong to the corresponding owners</p>
</div>

shop/templates/header.html
{% load static %}
<header class="header d-flex flex-row mx-5 mt-3 justify-content-between">
    <div class=" d-flex justify-content-start" style="text-align: center;">
        <div class="d-flex flex-row text-light">
            <h1><a href="{% url 'shop:home' %}" class="link-underline link-underline-opacity-0 link-light">WEB Games<i class="fa-solid fa-gamepad fa-xl m-3 mt-4"></i></a>
            </h1>
            
        </div>
    </div>
    <div class="nav-item d-flex justify-content-end text-light" style="text-align: center;">
        <ul class="d-flex justify-content-end">
            <i class="fa-solid fa-user fa-2xl m-3 mt-4"></i>
            {% if user.is_authenticated %}
            <a class = "m-2 nav-link"href="{% url 'account' %}">Hi {{user.username}}</a>
            {% else %}
            <a class="nav-link m-2" href="{% url 'login' %}">Sign in</a>
            {% endif %}


        </ul>
        <ul class="d-flex justify-content-end">
            <i class="fa-solid fa-cart-shopping fa-2xl m-3 mt-4"></i>
            <a class="nav-link m-2" href="{% url 'cart:cart_detail' %}">Basket 
                {% if item_count > 0 %}
                    <a class="nav-link mt-2" href="{% url 'cart:cart_detail' %}"><i
                            class="">{{item_count}}</i></a>

                {% endif %}</a>
        </ul>
        </ul>
    </div>
</header>

shop/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="text-light px-5">
        <h1>Featured</h1>
    </div>
        <div class="container-fluid d-flex justify-content-between text-light px-5  ">
            <img class="" style="width: 20rem " src="{% static 'images/Farcry.png' %}" alt="GtaV">
            <img class="" style="width: 20rem " src="{% static 'images/Rust.png' %}" alt="Rust">
            <img class="" style="width: 20rem " src="{% static 'images/Forza.png' %}" alt="ModernWarfare3">
        </div>


{% endblock %}

shop/templates/navbar.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
</head>
<nav class="px-5 mt-1 mb-4">
  <div class="d-flex justify-content-start" style="width: 25rem">
    <button class="catagories text-light btn dropdown-toggle"type="button"id="dropdownMenuButton1"data-bs-toggle="dropdown"aria-expanded="false">
      Catagories
    </button>
    <ul class="nav-link text-light">
      <ul class="catagories dropdown-menu">
        {% for cat in links %}
        <li>
          <a class="text-light dropdown-item" href="{{ cat.get_absolute_url }}">
            {{cat.name}}</a
          >
        </li>
        {% endfor %}
      </ul>
    </ul>

    <button class="mx-1 bestsellers btn text-light"type="button"aria-expanded="false">
      <a href="{% url 'shop:bestsellers' %}" class="text-light link-underline link-underline-opacity-0 ">Bestsellers</a>
    </button>
  </div>

  <div class="d-flex text-light">
    <form class="nav-item"style="width: 25rem"action="{% url 'search_app:searchResult' %}"method="get">
      <input class="form-control"type="search"placeholder="Search"aria-label="Search"name="q"
      />
    </form>
  </div>
</nav>